-- Hiking MVP database schema
-- Safe to run on a fresh Supabase project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  city text,
  experience_level text check (experience_level in ('beginner','intermediate','advanced')),
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hikes (
  id uuid primary key default gen_random_uuid(),
  organizer_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  location_name text not null,
  starts_at timestamptz not null,
  difficulty text not null check (difficulty in ('easy','moderate','hard')),
  distance_km numeric(6,2),
  max_participants integer check (max_participants is null or max_participants >= 2),
  status text not null default 'open' check (status in ('open','full','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.join_requests (
  id uuid primary key default gen_random_uuid(),
  hike_id uuid not null references public.hikes(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  message text,
  status text not null default 'pending' check (status in ('pending','accepted','rejected','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hike_id, user_id)
);

create table if not exists public.participants (
  hike_id uuid not null references public.hikes(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (hike_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  hike_id uuid not null references public.hikes(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists hikes_starts_at_idx on public.hikes(starts_at);
create index if not exists hikes_organizer_id_idx on public.hikes(organizer_id);
create index if not exists join_requests_hike_id_idx on public.join_requests(hike_id);
create index if not exists join_requests_user_id_idx on public.join_requests(user_id);
create index if not exists participants_user_id_idx on public.participants(user_id);
create index if not exists messages_hike_created_idx on public.messages(hike_id, created_at);

alter table public.profiles enable row level security;
alter table public.hikes enable row level security;
alter table public.join_requests enable row level security;
alter table public.participants enable row level security;
alter table public.messages enable row level security;

drop policy if exists "profiles are publicly readable" on public.profiles;
create policy "profiles are publicly readable"
on public.profiles for select
using (true);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "hikes are publicly readable" on public.hikes;
create policy "hikes are publicly readable"
on public.hikes for select
using (true);

drop policy if exists "authenticated users create hikes" on public.hikes;
create policy "authenticated users create hikes"
on public.hikes for insert
with check (auth.uid() = organizer_id);

drop policy if exists "organizers update own hikes" on public.hikes;
create policy "organizers update own hikes"
on public.hikes for update
using (auth.uid() = organizer_id)
with check (auth.uid() = organizer_id);

drop policy if exists "organizers delete own hikes" on public.hikes;
create policy "organizers delete own hikes"
on public.hikes for delete
using (auth.uid() = organizer_id);

drop policy if exists "requester or organizer reads join requests" on public.join_requests;
create policy "requester or organizer reads join requests"
on public.join_requests for select
using (
  auth.uid() = user_id
  or exists (
    select 1 from public.hikes h
    where h.id = hike_id and h.organizer_id = auth.uid()
  )
);

drop policy if exists "users request to join" on public.join_requests;
create policy "users request to join"
on public.join_requests for insert
with check (auth.uid() = user_id);

drop policy if exists "users cancel own pending requests" on public.join_requests;
create policy "users cancel own pending requests"
on public.join_requests for update
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status in ('pending','cancelled'));

drop policy if exists "organizers manage join requests" on public.join_requests;
create policy "organizers manage join requests"
on public.join_requests for update
using (
  exists (
    select 1 from public.hikes h
    where h.id = hike_id and h.organizer_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.hikes h
    where h.id = hike_id and h.organizer_id = auth.uid()
  )
);

drop policy if exists "participants are publicly readable" on public.participants;
create policy "participants are publicly readable"
on public.participants for select
using (true);

drop policy if exists "organizers add participants" on public.participants;
create policy "organizers add participants"
on public.participants for insert
with check (
  exists (
    select 1 from public.hikes h
    where h.id = hike_id and h.organizer_id = auth.uid()
  )
);

drop policy if exists "organizers remove participants" on public.participants;
create policy "organizers remove participants"
on public.participants for delete
using (
  exists (
    select 1 from public.hikes h
    where h.id = hike_id and h.organizer_id = auth.uid()
  )
);

drop policy if exists "group members read messages" on public.messages;
create policy "group members read messages"
on public.messages for select
using (
  exists (
    select 1 from public.hikes h
    where h.id = hike_id and h.organizer_id = auth.uid()
  )
  or exists (
    select 1 from public.participants p
    where p.hike_id = hike_id and p.user_id = auth.uid()
  )
);

drop policy if exists "group members send messages" on public.messages;
create policy "group members send messages"
on public.messages for insert
with check (
  auth.uid() = sender_id
  and (
    exists (
      select 1 from public.hikes h
      where h.id = hike_id and h.organizer_id = auth.uid()
    )
    or exists (
      select 1 from public.participants p
      where p.hike_id = hike_id and p.user_id = auth.uid()
    )
  )
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
